### ISSUE TITLE
About Steps Settings

### ISSUE THREAD

**Issue by Ranceeeee** [lsj2408/Transformer-M#1]
Thank you for your release of Transformer-M. About the settings of steps, warmup_ steps and total_ steps, do I need to divide the settings of steps by the number of GPUs used? Because I observed during training that the number of steps in each epoch of multi -gpu parallel will decrease, but the program still counts the steps according to the single card.

**Comment by lsj2408** [comment]
Thanks for using our code~ If you want to reproduce our results, you should keep both warmup_steps, total_steps and the total batch size (4*256=1024). If you want to explore the settings, feel free to try them as you wish.

**Comment by Ranceeeee** [comment]
> Thanks for using our code~ If you want to reproduce our results, you should keep both warmup_steps, total_steps and the total batch size (4*256=1024). If you want to explore the settings, feel free to try them as you wish.

How many epochs do you need to train to use your default settings?

**Comment by lsj2408** [comment]
For the default setting, the number of epochs is roughly 454.

**Comment by lsj2408** [comment]
If you have further questions on this topic, feel free to reopen this issue~
