### ISSUE TITLE
tasks for finetuning qm9  

### ISSUE THREAD

**Issue by koalaaaaaaaaa** [lsj2408/Transformer-M#12]
Hi, Thank you for your code for finetuning qm9, I have a small question on the corresponding relationship between `task_idx` and specific `task`.
do you mean that the correspondence is as follows?
![2a5a3a27e2c9b27ef0cce5efffe46a9](https://user-images.githubusercontent.com/59307253/229337344-0007439b-9314-4a93-9d42-35c2a6a3cfe2.png)
![f7692d06c51c1fa6b289dc8e35509bd](https://user-images.githubusercontent.com/59307253/229337351-697d8470-c4d3-4dfd-bbc2-6735835eeff2.png)
Thank you for your kindest reply.

**Comment by lsj2408** [comment]
Yes, you are right. The task_idx denotes the corresponding target index in this table.
