### ISSUE TITLE
Question about inputting only 2D Data

### ISSUE THREAD

**Issue by AlexWei21** [lsj2408/Transformer-M#15]
Hi! 

Thank you for introducing such an interesting model to us and sharing the code! 

I'm trying to run the model only on 2D structures, would you mind providing a script for using only 2D structures to train the model (Like for PCQM4M-LSC-V2)?

I tried to change the dataset_name and set add_3D to false in the sample train script for 3D data in the readme file, but that doesn't work. I looked into the code and found that in the tasks/graph_prediction.py file , Class GraphPredictionTask, and load_dataset function, when calling BatchedDataDatset, when it set the dataset_version to "2D" for PCQM4M-LSC-V2, it gives the error in criterions/graph_predictions.py line 45: ori_pos = sample['net_input']['batched_data']['pos'], KeyError: 'pos'.

Thank you so much!

**Comment by sunyrain** [comment]
Same Question

**Comment by sunyrain** [comment]
> Hi!
> 
> Thank you for introducing such an interesting model to us and sharing the code!
> 
> I'm trying to run the model only on 2D structures, would you mind providing a script for using only 2D structures to train the model (Like for PCQM4M-LSC-V2)?
> 
> I tried to change the dataset_name and set add_3D to false in the sample train script for 3D data in the readme file, but that doesn't work. I looked into the code and found that in the tasks/graph_prediction.py file , Class GraphPredictionTask, and load_dataset function, when calling BatchedDataDatset, when it set the dataset_version to "2D" for PCQM4M-LSC-V2, it gives the error in criterions/graph_predictions.py line 45: ori_pos = sample['net_input']['batched_data']['pos'], KeyError: 'pos'.
> 
> Thank you so much!

Have you found the solution?

**Comment by sunyrain** [comment]
I change the parameter "mode_prob: ${mode_prob} for {2D+3D, 2D, 3D}" to 0,1,0, and it works for me.

**Comment by AlexWei21** [comment]
Sorry for missing this, I eventually solved it by tuning the mode_prob as well!
