### ISSUE TITLE
How to obtain the embedding of molecular conformation

### ISSUE THREAD

**Issue by 1121091694** [lsj2408/Transformer-M#4]
Great Work! 
Input：atom_type + xyz
How can we get the embedding of atom and xyz?

**Comment by lsj2408** [comment]
The embedding of atom: https://github.com/lsj2408/Transformer-M/blob/45647e143a5282e0e97117969396446084bcf1ab/Transformer-M/modules/transformer_m_layers.py#L25 

The attention bias of 3D position: https://github.com/lsj2408/Transformer-M/blob/45647e143a5282e0e97117969396446084bcf1ab/Transformer-M/modules/transformer_m_layers.py#L149
