### ISSUE TITLE
question about chechpoint

### ISSUE THREAD

**Issue by Jesse-zjx** [lsj2408/Transformer-M#5]
Thanks for your amazing work! 
I wonder why download link of checkpoint is not to a '*.pt' file?

**Comment by lsj2408** [comment]
Hi, could you please check the link again? By my side the link works well.

**Comment by Jesse-zjx** [comment]
hey. I just check the newest link of L12_old, it does work. but the links of L12 and L18 are still not work. when I download it, it will give me a zip file. after unzip, a folder called archive, no *.pt inside. maybe problem of macos?

**Comment by lsj2408** [comment]
Hi~ You could directly load the L12 via pytorch: ckpt=torch.load('L12')
