### ISSUE TITLE
Training on QM9

### ISSUE THREAD

**Issue by RobDHess** [lsj2408/Transformer-M#8]
Hi,

Would it be possible to provide the commands for training a model on QM9 from scratch? This is mentioned in appendix B5 when investigating the effectiveness of pre-training. 

Kind regards, 

Rob

**Comment by lsj2408** [comment]
Hi, I have released the fine-tuning code of QM9. For training the Transformer-M model from scratch, you could simply add 'export no_pretrain="true" ' before running the finetune_qm9.sh.
